### ISSUE TITLE
What audio formats does the program support?

### ISSUE THREAD

**Issue by rotemdan** [echogarden-project/echogarden#18]
"What audio formats does the program support? It seems not all audio can be used for alignment."

_Originally posted by @Tendaliu in https://github.com/echogarden-project/echogarden/issues/11#issuecomment-1663495226_

**Comment by rotemdan** [comment]
@Tendaliu

For input audio, all operations accepting audio inputs, including alignment, should support any audio format that's supported by FFMpeg, this even includes many video formats like MP4 and MKV.

For output audio formats, I've limited the file extensions to `wav`, `mp3`, `opus`, `m4a`, `ogg`, `flac`.

These are all web-friendly formats, that are relatively open that are supported by web browsers and most players.

It's possible to add support for closed or exotic formats as output, like, `aiff`, `amr`, `ac3`, `spx`, etc. but most likely they are not are hardly going to be used by anyone, or have better alternatives.

**Comment by Tendaliu** [comment]
The audio generated by the program can be used for Alignment correctly. However, if I use my own audio, or if I convert the format of the audio generated by the program, the following issues arise:
C:\Users\Sunda>"C:\ProgramData\node-v18.17.0-win-x64\echogarden.cmd" align "D:\素材\test.mp4" "D:\1691047884\text.txt"
Echogarden v0.10.0

Prepare for alignment.. 680.4ms
No language specified. Detecting language.. 137.7ms
Language detected: Chinese (zh)
Get espeak voice list and select best matching voice.. 158.2ms
Selected voice: 'sit/cmn' (cmn, Chinese)
Load alignment module.. 0.5ms
Create alignment reference with eSpeak.. 2474.9ms
Compute reference MFCC features.. 276.2ms
Compute source MFCC features..
C:\Users\Sunda>
![image](https://github.com/echogarden-project/echogarden/assets/86396088/4c41372f-198e-4e35-88c3-9b1280f08716)

**Comment by rotemdan** [comment]
@Tendaliu 
Thanks for the details. I've tested an `mp4` video as input for `align` to at least see if it worked, and it did. FFMpeg extracted the audio track from the video, as I expected.

What you seem to be encountering is that the audio feature (MFCC) extraction for the source audio is taking a lot of time (or possibly delayed or paused in some way, which is unlikely). Otherwise, it seems that the audio was decoded correctly from the `mp4` file you gave it.

If the audio feature extraction stage doesn't seem to end, can you check if CPU usage is at 100% for at least one core, or maybe if memory usage is growing? Can you try a different `mp4` media file as input to see if the problem is specific for that particular audio file?

**Comment by rotemdan** [comment]
Thanks a lot for the bug report! I downloaded [the same video](https://www.youtube.com/watch?v=yEDUSn214y4) using the `yt-dlp` tool, and reproduced the issue (it fails when extracting MFCC features without a visible error).

I'll run it with the debugger to see what is happening. In any case, I'll try to ensure there's an error message if there is any problem with the input audio.

**Comment by Tendaliu** [comment]
Hi, I have a suggestion. When using the transcript alignment function, could the program try to split sentences at commas and periods as much as possible? Sometimes a sentence doesn't reach the characters limit, but it is still divided into two subtitles by the program. BTW, the  transcript  is Chinese

**Comment by rotemdan** [comment]
@Tendaliu I moved the question to a [new issue](https://github.com/echogarden-project/echogarden/issues/19). It's important to me to have the issue tracker easy to search since others may look for the same question in the future.

I'm assuming the issue described here is resolved so I'll close this issue.
