### ISSUE TITLE
a problem ocurred in text-to-speech

### ISSUE THREAD

**Issue by yhown589** [echogarden-project/echogarden#39]
the following is my code, it successfully generates a.mp3, but this file cannot nomally play.
what's the problem in this code
```
import {synthesize} from "echogarden"
import fs from "fs"

let SynthesisOptions = {
    "language": "en",
}

synthesize("hello world", SynthesisOptions).then(
    (result) => {
        fs.writeFileSync("F:\\example\\a.mp3", result.audio.audioChannels[0])
    }
)
```

**Comment by rotemdan** [comment]
By default it outputs raw 32 bit float audio. To get a different codec, you need to specify the codec, like to MP3:

```js
import { synthesize } from "echogarden"
import fs from "fs"

let synthesisOptions = {
	"language": "en",
	"outputAudioFormat": {
		"codec": "mp3"
	}
}

synthesize("hello world", synthesisOptions).then(
	(result) => {
		fs.writeFileSync("F:\\example\\a.mp3", result.audio)
	}
)
```

The returned object has this type:
```ts
interface SynthesisResult {
	audio: RawAudio | Buffer
	timeline: Timeline
	language: string
	voice: string
}
```

So without specifying the codec, what you get in the `audio` property is a `RawAudio` object, which looks like this:

```ts
export type RawAudio = {
	audioChannels: Float32Array[]
	sampleRate: number
}
```

When you specify a codec, you get a Node.js Buffer instead, containing the encoded binary data for the audio.

This is documented in the API documentation and in the TypeScript definitions. It would be much easier to use the library from TypeScript, where you get autocomplete suggestions for all the types.

**Comment by yhown589** [comment]
thank u, it works. I'm a beginner in programming and my fist language is not Engnlish.
This two points make it very difficult for me to learn, read, and understande the code, But I will try my struggles to do it.
thank you very much for solving my problem again.
