### ISSUE TITLE
a error threw when Extract timeline for part

### ISSUE THREAD

**Issue by yhown589** [echogarden-project/echogarden#58]
atfer aligning audio, proceed to the step of Extract timeline for part, an error was throw:
![PixPin_2024-06-11_05-25-58](https://github.com/echogarden-project/echogarden/assets/158656896/a065cb61-b596-4894-b669-ac8e059c6b5a)
I enter the method that threw the error and found:
![PixPin_2024-06-11_05-28-23](https://github.com/echogarden-project/echogarden/assets/158656896/ab5731de-0fbd-4756-8649-0e58600e7482)
I guess that it maybe caused by recognizing the definition of word

text: `That allows the firm to start mass production. The EH216.S is the first flying car to receive such regulatory approval anywhere in 
the world. Ehang has competition in China, an EV toll from Autoflight, a Shanghai based firm, obtained a type certificate from the CAAC in March, signifying approval of its design.`

**Comment by rotemdan** [comment]
Yes, this issue has been known to me for several months and included in [my tasklist](https://github.com/echogarden-project/echogarden/blob/main/docs/Tasklist.md) (the first issue). 

It occurs when the recognizer produces a different word segmentation than the one that's use to convert a word timeline to a sentence / segment timeline (typically uses the `cldr-segmentation` by default, `jieba-wasm` for Chinese, `kuromoji` for Japanese).

A lot of the times it occurs is when a dot character in the middle of the word is parsed as a sentence separator in one approach, and as a native part of the word in another. For example `EH216.S` is parsed as a single word by the recognizer but as two words, where the `.` is a sentence separator, in another.

I'll need to find a plan on how to prevent this from occuring. I'm not sure exactly how at the moment.

**Comment by rotemdan** [comment]
I added a potential fix / workaround for this issue on the new 1.6.0 release.

See [this comment on the other thread](https://github.com/echogarden-project/echogarden/issues/67#issuecomment-2393027549) for more information.

**Comment by rotemdan** [comment]
Issue should be fixed.

Closing for now.
