### ISSUE TITLE
Wasm SIMD unsupported On AMD Ryzen

### ISSUE THREAD

**Issue by smoores-dev** [echogarden-project/echogarden#73]
Hiii it's me again. Storyteller just updated to echogarden 2.0.3 last week, and it's largely going great! But a user just reported this issue:

```
RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Compiling function #8 failed: Wasm SIMD unsupported @+9386). Build with -sASSERTIONS for more info.
    at abort (file:///app/node_modules/@echogarden/speex-resampler-wasm/speex-resampler.js:9:4948)
    at file:///app/node_modules/@echogarden/speex-resampler-wasm/speex-resampler.js:9:6031
```

## System Info:

Running in a docker container on a Proxmox VM (debian 12)
CPU: AMD Ryzen 7 5700G

In case it's helpful, it seems like undici ran into this at some point as well: https://github.com/nodejs/undici/issues/2934

**Comment by smoores-dev** [comment]
This would be running on Node.js 20. I have a release that should be out today using Node.js 22, so we can see if that helps at all, but that doesn't seem incredibly likely to me :confused:. I'll have them give that a shot and report back in a bit!

**Comment by rotemdan** [comment]
I published [`v2.0.4`](https://github.com/echogarden-project/echogarden/releases/tag/v2.0.4) with non-SIMD fallback for both `pffft` and `speex-resampler`.

**Comment by smoores-dev** [comment]
Thank you so much, you're the best. I've just pushed out a new Storyteller release; I'll confirm with this user that their issue is resolved and then update back here

**Comment by smoores-dev** [comment]
This is confirmed to have resolved the issue that the user was reporting! I also got some more info, explaining why this was unexpectedly not working for such a modern CPU:

https://gitlab.com/smoores/storyteller/-/issues/161#note_2226264992

> As it turns out, the issue was a misconfiguration on my part. As I mentioned in my OP, I’m running this in a Docker container inside a VM on Proxmox. It turns out I had configured the VM with the wrong CPU type (well, no type at all to be specific). After switching from kvm4 to host, everything started working as expected.

Their VM was defaulting to a different CPU architecture. They confirmed, though, that this update works with that default architecture, which didn't support SIMD, as well!
