### ISSUE TITLE
Could echogarden export `WhisperCppModelId` from the API?

### ISSUE THREAD

**Issue by smoores-dev** [echogarden-project/echogarden#77]
At the moment, the only way to access this type is with a deep import (`echogarden/dist/recognition/WhisperCppSTT`). But since it's used to type the `recognize` interface, it's nice to be able to use it as a return type for functions or in a type annotation or `satisfies` annotation.

**Comment by rotemdan** [comment]
I was sort of wondering whether I'd consider this is a "workaround" or not.

So, I don't think it's a workaround, and it's a pattern I use myself when I have TypeScript modules that have to talk to each other. There are some reason to prefer this:

* It means that the inner types (the hidden types), don't have to be fully "stable", they can be renamed but the type expression would still work. It's a kind of type encapsulation.
* It removes complexity from maintaining type exports when there is a very large number of associated types.
* It allows the inner types to be renamed without breaking the API types - meaning the inner types don't have to be stabilized as part of the API.


I think just that TypeScript doesn't use a very nice syntax for it (I actually was one of the people who suggested / requested that feature, in about 2015-2016 maybe).

Imagine you could write it like this:
```ts
type WhisperCppModelId = RecognitionOptions.whisperCpp!.model
```
Using `.` and `!` look much nicer and intuitive, but for various reasons they chose to use the square bracket syntax (`['']`) instead. I don't remember why exactly, maybe for some technical reasons.

Another option could be some sort of `typeof options.whisperCpp!.model` expression, but you'll need to make an instance of `RecognitionOptions` first, and only then get the type from it.

**Comment by smoores-dev** [comment]
I appreciate you walking through your thinking here. I have definitely run into situations like this before with larger libraries, and the idea of doing something like `NonNullable<RecognitionOptions['whisperCpp']>['model']` seems fine to me. Echogarden has such a large surface area for its API options that I think you're right; it would be overly burdensome to export (and worry about maintaining backwards compatibility with) every type that makes up a part of that interface.

I'll close this issue and just grab the type I need from `RecognitionOptions`, as you suggested! Thanks @rotemdan.
